### ISSUE TITLE
MatPlotLib is going to give us some issues with distributable's 

### ISSUE THREAD

**Issue by EclectickMedia** [EclectickMedia/PingStats#15]
# Preamble

Currently, with the aims of not having to install Python to the user's computer, we find ourselves in [between a rock and a hard place](https://depressionlighthouse.files.wordpress.com/2014/10/simpsons.gif). `matplotlib` uses largely framework based, OS dependant graphical backends (i.e [GTK](http://www.pygtk.org), [WX](http://www.wxpython.org), [Qt5](pyqt5 examples), [etc](http://matplotlib.org/faq/virtualenv_faq.html).). 

Most of these backends result in a broken, and inconsistent build across platforms.

--------

Due to the fact that `matplotlib` uses essentially the full Python standard library, a lot of its functionality becomes broken on making a distributable. As of writing this, I am unsure as to what needs to be done to fix this. I have done a bit of research and found that PyInstaller should "play nice" with `matplotlib` with a bit of configuration. I have also come to find that MacOSx doesn't like to play nice with compiling programs using `matplotlib` to a distributable, and as such we need to get a *NIX machine compiling the software.

**Comment by EclectickEclipse** [comment]
With the inclusion of an install script, is it really necessary to package?

**Comment by EclectickMedia** [comment]
Our best bet is to use Agg as the backend. This is what V0.09.03 is currently running off of.

V0.09.03 also has an install script that handles Python installation and PingStats "build" automatically for end users.

**Comment by EclectickMedia** [comment]
See #24 for further explanation.
