### ISSUE TITLE
Error attempting to run

### ISSUE THREAD

**Issue by frawst** [EclectickMedia/PingStats#36]
Running PingStats.py

```python
Traceback (most recent call last):
  File "A:/Maya/Projects/PingStats/PingStats.py", line 30, in <module>
    import Plot
  File "A:\Maya\Projects\PingStats\Plot.py", line 5, in <module>
    import PingStats as ping
  File "A:\Maya\Projects\PingStats\PingStats.py", line 31, in <module>
    from pythonping import ping as pyping
ImportError: cannot import name 'ping'
```

Installing pythonping:

```
creating build
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\EGG-INFO
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
creating build\scripts-3.4
error: file 'A:\Maya\Projects\PingStats\pythonping\ping.py' does not exist
```

**Comment by frawst** [comment]
I am just trying to make sure I have all the dependencies before you dive into debugging with my machine

**Comment by EclectickMedia** [comment]
The branch you need to use is [l4m3rx's repo](https://github.com/l4m3rx/python-ping). 

I have the code installed as a directory within my local code as follows:
```
PingStats/
|--- PingStats files and folders
|--- pythonping  # the folder containing l4m3rx's code repo
```

**Comment by EclectickMedia** [comment]
```
creating build
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\EGG-INFO
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
creating build\scripts-3.4
error: file 'A:\Maya\Projects\PingStats\pythonping\ping.py' does not exist
```

This code does not output from either mine, or l4mr3x's code. Are you sure you have the right repo's installed?

Remember to use `git clone` to get this code.

l4mr3x's repo may require you to rename the folder that `git clone` results in.

**Comment by EclectickMedia** [comment]
Could you attach your version info? `sudo python3 PingStats -v` and `python -v`

**Comment by frawst** [comment]
I still have to get the dependencies installed, I think it's working after some minor tweaks - python wouldn't import l4mr3x's ping since the container had a dash in it, so I removed it and it works, but I'm not sure that python-ping is going to like that much in the long term.

**Comment by frawst** [comment]
```
A:\Maya\Projects\PingStats>py PingStats.py -v
PingStats Version 2.0.01 (C) Ariana Giroux, Eclectick Media Solutions. circa Sun
 Nov 13 06:39:04 2016

A:\Maya\Projects\PingStats>py -V
Python 3.4.3
```

**Comment by EclectickMedia** [comment]
Python is picky about dashes, and its an ongoing discussion to rename the package.

That is the fix that I employed.

Python 3.4.3 is fine, my software just is not executable by 2.7
